# Merge Datasets(Trade & Sentiment)

In [1]:
import pandas as pd
import os

## Load Cleaned Datasets

In [4]:
trade_path = "../data/preprocessed/historical_data/cleaned_historical_data.csv"
sentiment_path = "../data/preprocessed/sentiment_data/sentiment_clean.csv"

In [6]:
trades_df = pd.read_csv(trade_path, parse_dates = ['date'])
sentiment_df = pd.read_csv(sentiment_path, parse_dates = ['date'])

## Align Date formats & timezones

### Ensure both are in UTC date format

In [7]:
trades_df['date'] = pd.to_datetime(trades_df['date']).dt.date
sentiment_df['date'] = pd.to_datetime(sentiment_df['date']).dt.date

## Merge datasets on Date

In [8]:
merged_df = pd.merge(trades_df, sentiment_df, on = 'date', how = 'left')

## Handle Missing Sentiment

In [11]:
merged_df = merged_df.sort_values("date")
merged_df['value'] = merged_df['value'].ffill().bfill()
merged_df['classification'] = merged_df['classification'].ffill().bfill()

## Save merged dataset

In [12]:
merged_df.to_csv("../data/Merged Data/merged_trades_sentiment.csv", index=False)

## Merged Dataset Overview

In [13]:
merged_df.shape

(211224, 31)

In [14]:
merged_df.head()

,account,coin,execution_price,size_tokens,size_usd,side,timestamp_local,start_position,direction,closed_pnl,...,year,is_weekend,win,abs_size_tokens,abs_size_usd,roi,timestamp_y,value,classification,sentiment_score
83771,0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891,ETH,1898.6,0.0722,137.08,BUY,2023-05-01 01:06:00+05:30,0.1791,Open Long,0.0,...,2023,1,0,0.0722,137.08,0.0,2023-04-30 05:30:00+00:00,60,Greed,75
83770,0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891,ETH,1897.9,0.0824,156.39,BUY,2023-05-01 01:06:00+05:30,0.0967,Open Long,0.0,...,2023,1,0,0.0824,156.39,0.0,2023-04-30 05:30:00+00:00,60,Greed,75
83769,0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891,ETH,1897.9,0.0967,183.53,BUY,2023-05-01 01:06:00+05:30,0.0000,Open Long,0.0,...,2023,1,0,0.0967,183.53,0.0,2023-04-30 05:30:00+00:00,60,Greed,75
39062,0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23,BTC,41867.0,0.0150,628.00,SELL,2023-12-05 03:11:00+05:30,0.0000,Open Short,0.0,...,2023,0,0,0.0150,628.00,0.0,2023-12-04 05:30:00+00:00,74,Greed,75
39061,0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23,ETH,2231.0,3.8932,8685.73,BUY,2023-12-05 03:11:00+05:30,7.3187,Open Long,0.0,...,2023,0,0,3.8932,8685.73,0.0,2023-12-04 05:30:00+00:00,74,Greed,75

In [18]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 211224 entries, 83771 to 60888
Data columns (total 31 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   account           211224 non-null  object
 1   coin              211224 non-null  object
 2   execution_price   211224 non-null  float64
 3   size_tokens       211224 non-null  float64
 4   size_usd          211224 non-null  float64
 5   side              211224 non-null  object
 6   timestamp_local   211224 non-null  object
 7   start_position    211224 non-null  float64
 8   direction         211224 non-null  object
 9   closed_pnl        211224 non-null  float64
 10  transaction_hash  211224 non-null  object
 11  order_id          211224 non-null  int64
 12  crossed           211224 non-null  bool
 13  fee               211224 non-null  float64
 14  trade_id          211224 non-null  float64
 15  timestamp_x       211224 non-null  float64
 16  timestamp_utc     211224 non-null  object
 17  date              211224 non-null  object
 18  hour              211224 non-null  int64
 19  weekday           211224 non-null  int64
 20  week              211224 non-null  int64
 21  year              211224 non-null  int64
 22  is_weekend        211224 non-null  int64
 23  win               211224 non-null  int64
 24  abs_size_tokens   211224 non-null  float64
 25  abs_size_usd      211224 non-null  float64
 26  roi               211224 non-null  float64
 27  timestamp_y       211224 non-null  object
 28  value             211224 non-null  int64
 29  classification    211224 non-null  object
 30  sentiment_score   211224 non-null  int64
dtypes: bool(1), float64(11), int64(9), object(10)
memory usage: 50.2+ MB

In [19]:
merged_df.describe()

,execution_price,size_tokens,size_usd,start_position,closed_pnl,order_id,fee,trade_id,timestamp_x,hour,weekday,week,year,is_weekend,win,abs_size_tokens,abs_size_usd,roi,value,sentiment_score
count,211224.000000,2.112240e+05,2.112240e+05,2.112240e+05,211224.000000,2.112240e+05,211224.000000,2.112240e+05,2.112240e+05,211224.000000,211224.000000,211224.000000,211224.000000,211224.000000,211224.000000,2.112240e+05,2.112240e+05,211224.000000,211224.000000,211224.000000
mean,11414.723350,4.623365e+03,5.639451e+03,-2.994625e+04,48.749001,6.965388e+10,1.163967,5.628549e+14,1.737744e+12,12.234500,2.551405,18.134142,2024.747978,0.192757,0.411265,4.623365e+03,5.639451e+03,0.018991,51.610044,52.948529
std,29447.654868,1.042729e+05,3.657514e+04,6.738074e+05,919.164828,1.835753e+10,6.758854,3.257565e+14,8.689920e+09,6.960365,1.921552,15.513679,0.437996,0.394465,0.492064,1.042729e+05,3.657514e+04,0.845727,20.981819,32.326780
min,0.000005,8.740000e-07,0.000000e+00,-1.433463e+07,-117990.104100,1.732711e+08,-1.175712,0.000000e+00,1.680000e+12,0.000000,0.000000,1.000000,2023.000000,0.000000,0.000000,8.740000e-07,0.000000e+00,-384.406426,10.000000,0.000000
25%,4.854700,2.940000e+00,1.937900e+02,-3.762311e+02,0.000000,5.983853e+10,0.016121,2.810000e+14,1.740000e+12,6.000000,1.000000,8.000000,2024.000000,0.000000,0.000000,2.940000e+00,1.937900e+02,0.000000,32.000000,25.000000
50%,18.280000,3.200000e+01,5.970450e+02,8.472793e+01,0.000000,7.442939e+10,0.089578,5.620000e+14,1.740000e+12,13.000000,2.000000,13.000000,2025.000000,0.000000,0.000000,3.200000e+01,5.970450e+02,0.000000,49.000000,50.000000
75%,101.580000,1.879025e+02,2.058960e+03,9.337278e+03,5.792797,8.335543e+10,0.393811,8.460000e+14,1.740000e+12,18.000000,4.000000,17.000000,2025.000000,0.000000,1.000000,1.879025e+02,2.058960e+03,0.010318,72.000000,75.000000
max,109004.000000,1.582244e+07,3.921431e+06,3.050948e+07,135329.090100,9.014923e+10,837.471593,1.130000e+15,1.750000e+12,23.000000,6.000000,52.000000,2025.000000,1.000000,1.000000,1.582244e+07,3.921431e+06,3.403550,94.000000,100.000000